FROM node:alpine as build

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM node:alpine as production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

EXPOSE 3000

RUN yarn install --only=prod


COPY . .

COPY --from=build /usr/src/app/dist ./dist

CMD [ "node", "dist/main" ]