name: Docker

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t okp980/wemeet-backend
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{DOCKER_USERNAME}} --password-stdin
      - run: docker push okp980/wemeet-backend
